### ISSUE TITLE
Can't open normally under windows

### ISSUE THREAD

**Issue by roy20001215** [horsaen/afreeca-downloader#5]
as shown in the video

https://github.com/horsaen/afreeca-downloader/assets/52929120/0f471c79-99ae-4bda-bae5-056ef391af7c

**Comment by horsaen** [comment]
will work on asap 🫡

**Comment by horsaen** [comment]
hey !! so i'm unable to replicate the issue on windows 10 v22H2 with the newest version of the downloader, it's also confirmed working on arch linux on the 6.8.9 kernel and some random version of debian.

since running the exe from the file does not give any output on exit, could you please run the downloader from the command line ? thanks !!

**Comment by roy20001215** [comment]
The version I'm using is below because I don't know how to use the command line to execute the program.
版本	Windows 11 家用版
版本	23H2
安裝於	‎2022/‎12/‎14
OS 組建	22631.3447
體驗	Windows Feature Experience Pack 1000.22688.1000.0

**Comment by horsaen** [comment]
no worries !! i made a video for you, just make sure to drag the exe to your user folder since it's easier, you can move it to wherever you want afterwards

https://github.com/horsaen/afreeca-downloader/assets/68721015/8c684148-a806-420e-a73c-b2abb4c7f2a8
