### ISSUE TITLE
nothing coming up for -concurrent

### ISSUE THREAD

**Issue by ghost** [horsaen/afreeca-downloader#6]
im pretty new to all this so apologies if this is a simple error, I did try looking around for answers though. when i go to -concurrents nothing shows up even though I have names saved in users as instructed. Also some downloads of streams also doesn't work, specifically ones with high viewers or age restricted ones i think. I saved the correct cookies value and this is only for afreeca (havent tried the others). Maybe it has something to with the way I saved the files for users and cookies? Any help would be appreciated thanks
attached are what it looks like 
![af](https://github.com/horsaen/afreeca-downloader/assets/153869873/e82c978c-381e-4627-940e-3b7b474aa035)
![af2](https://github.com/horsaen/afreeca-downloader/assets/153869873/7f94cb8e-ed9b-43af-894f-d7851cf1a6c9)

**Comment by horsaen** [comment]
hey !! thanks for the issue !!

just to clarify, the `users` file requires that the user and the platform are separated by both a comma AND a space, thus:

`pineapple3, afreeca`

exactly like that !! though i do appreciate the error code in the second image, thanks a ton :] the idx OOR error is reported when the downloader is unable to get the master playlist, either this could be due to the cookies, or there are cases where the stream is password protected, and the server refuses to give the master playlist w/o it. i still need to write logic to prevent it from just exiting, but these are the most common reasons.

also just tested it on a new virtual machine w/ the newest build, -concurrent seems to be working as intended :D

looking forward to getting this fixed for you

**Comment by ghost** [comment]
I appreciate the response, it must be something on my end then. Ill let you know if i figure it out, many thanks :)

**Comment by horsaen** [comment]
feel free to reach out on the discord or make another comment here--this issue will remain open until your issue is fixed, i'm interested in seeing what the cause of this is.. take care and good luck !!

**Comment by braynshan** [comment]
wow u r amazinh horsaen thx i have same issue waiting for fix. too much thxxxxx to u

**Comment by horsaen** [comment]
hey @braynshan, thanks for reaching out. as previously stated, the -concurrent flag is working intended on both Windows 10 and multiple Linux distros--which leads me to believe it's something on the client side, rather than the downloader itself.

to make a few things sure, what happens when you run -concurrent? is it similar to c0mfy's post? also, make sure that your file follows the correct naming scheme, and that your file permissions allow for your users file to be read.

hope this helps at least a little !! if not, feel free to stop by in the discord ^^

**Comment by braynshan** [comment]
> hey @braynshan, thanks for reaching out. as previously stated, the -concurrent flag is working intended on both Windows 10 and multiple Linux distros--which leads me to believe it's something on the client side, rather than the downloader itself.
> 
> to make a few things sure, what happens when you run -concurrent? is it similar to c0mfy's post? also, make sure that your file follows the correct naming scheme, and that your file permissions allow for your users file to be read.
> 
> hope this helps at least a little !! if not, feel free to stop by in the discord ^^

yes similar as c0mfy post right
